name: Package Image creator
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "image-creation" ]
  pull_request:
    branches: [ "image-creation" ]

jobs:
    # This job is to validate all the input values used in workflow.
    Image_creation:
      runs-on: ubuntu-latest
      environment: CSG_CRED
      steps:
        - uses: actions/checkout@v1
        - name: Script using  repo variable
          run: packer validate -syntax-only .
        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
             creds: ${{ secrets.CSG_AZURE_CRD }}
  
        - name: Packer Image
          run: |
            packer plugins install github.com/hashicorp/azure
            packer build -var-file="variables.pkrvars.hcl" image-creation.pkr.hcl

            
    
